<h1><?php echo $this->getProductList() ?></h1>
<p><?php echo $this->getVariableValue() ?></p>

<p><?php echo $this->getHelperData()->getJeanTrousersConfig('enable').' '.$this->getHelperData()->getJeanTrousersConfig('display_text') ?></p>
<p><?php echo $this->getHelperData()->getJeanShirtConfig('enable').' '.$this->getHelperData()->getJeanShirtConfig('display_text') ?></p>

<section class="slider">
    <div class="flexslider carousel">
        <ul class="slides">
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_cheesecake_brownie.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_lemon.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_donut.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_caramel.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_cheesecake_brownie.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_lemon.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_donut.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_caramel.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_cheesecake_brownie.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_lemon.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_donut.jpg" />
            </li>
            <li>
                <img src="http://flexslider.woothemes.com/images/kitchen_adventurer_caramel.jpg" />
            </li>
        </ul>
    </div>
</section>